### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by ayato-p** [redpen-cc/redpen#673]
`redpen --version` say `1.6.0`, however I was installed version `1.6.1` via releases page.

BTW, I'm using `curl` for downloading tarball, like
`curl -L -o redpen.tar.gz https://github.com/redpen-cc/redpen/releases/download/redpen-1.6.1/redpen-1.6.1.tar.gz`

Thanks.

**Comment by takahi-i** [comment]
Hello @ayato-p. Thank you very much for the comment on the wrong version number. Actually the version number flush with -h option but the version is v1.6.1. It is a human mistake. Unfortunately I am not able to reload another redpen zip file since the zip file and the SHA is depended by Homebrew and Maven central. 

Therefore I made another version, v1.6.2, which fix the version number bug.

https://github.com/redpen-cc/redpen/releases/tag/redpen-1.6.2

As for Homebrew, I also made pull request for the version.

https://github.com/Homebrew/homebrew-core/pull/2411

Hopefully this fix works for you.

I close this issue but let me know if you still have the bug reopening this issue or opening a new issue.
