### ISSUE TITLE
KatakanaEndHyphen - Changing the default dictionary

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#710]
We are using a different standard for the end hyphen of katakana words to the RedPen default. For example, our standard recommends 「コミュニティー」 but the RedPen default recommends 「コミュニティ」. As a result, 「コミュニティー」 is flagged. We can stop RedPen flagging 「コミュニティー」 by adding it to the KatakanaEndHyphen word list or dictionary, but this results in neither word being flagged. We want 「コミュニティ」 to be flagged. I tried adding 
 「コミュニティ」 -tab-  「コミュニティー」
to the SuggestExpression word list. This flags  「コミュニティ」 correctly and suggests  「コミュニティー」, but it also flags  「コミュニティー」 because it contains 「コミュニティ」. Is there any way to to prevent this, for example by disabling the default KatakanaEndHyphen dictionary?

**Comment by cmoen** [comment]
My understanding is that the validator implements the JIS Z8301 recommendation, which basically says that words or three or more characters should not end with the long vowel character.

I will leave Ito-san & co. to comment, but perhaps this rule is too strict in many cases?

Since the long vowel sound is a common spelling variation for Japanese, it might make sense to do consistency checks in a document, i.e. making sure the actual usages of a word are used consistently in a document so that we don't have コミュニティー and コミュニティ in the same document.

**Comment by edwardwoodward** [comment]
The system we are following is the "Japan Technical Communicators Association" style guide. I wouldn't like to say if one is any more valid than the other, but it would probably be advantageous for RedPen to offer both options. I think JTCA's is quite widely used.

**Comment by takahi-i** [comment]
Hello @edwardwoodward. Thank you very much for the report! " Is Japan Technical Communicatior Association style guid" available on-line?  If so could you please show the link for us to understand the specification.

**Comment by edwardwoodward** [comment]
I think the style guide as a whole is only available in printed form (http://www.jtca.org/publication/guide_jsg.html), but the katakana rules are available here:
http://www.jtca.org/standardization/katakana_guide_3_20150929.pdf

**Comment by takahi-i** [comment]
Thanks!

**Comment by edwardwoodward** [comment]
Sorry for the late reply. I missed your comment.
I just clicked the link and the pdf displays fine.
I also downloaded it and opened it locally and it seems OK.
