### ISSUE TITLE
Adding terms for Okurigana

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#714]
How does Okurigana decide which terms to flag? Is there a way to add to them or add a skip list?
I'm asking because RedPen is flagging 「過す」, which normally would be fair enough, but in this case, it is part of  「超過する」, which is legitimate usage. Is there any way to prevent this?

**Comment by takahi-i** [comment]
Hi @edwardwoodward. Thank you very much for the report. 
Okurigana validator just checks sentences with the inner dictionary. The following is the source file.

https://github.com/redpen-cc/redpen/blob/master/redpen-core/src/main/java/cc/redpen/validator/sentence/OkuriganaValidator.java

Currently Okurigana validator does not provide the user dictionary for skipping errors, but you can suppress the errors adding **suppress** annotation in the beginning of section. The section shows the usage of the suppress annotation.

http://redpen.cc/docs/latest/index.html#suppress-section

For now, I will close this issue, since we have many tasks reported from users.
