### ISSUE TITLE
Validating JSON data

### ISSUE THREAD

**Issue by stefanionescu** [redpen-cc/redpen#786]
Hi! I'm a newbie here on RedPen and I can't access any documentation on your website.

I just wanted to know if I can validate text using a custom xml which is exported from your website.

Right now I'm using a web address to validate but I want to switch to xml. I use this in a Java app.

**Comment by ocadaruma** [comment]
@stefanionescu Hi.
You can use custom XML which is exported from http://redpen.herokuapp.com/ . (or modifying `conf/redpen-conf-en.xml` in the [package](https://github.com/redpen-cc/redpen/releases/))

**Comment by stefanionescu** [comment]
Hmm ok. I use a "validate" method to process text while using a web address. Do I use the same "validate" method when I work with XML or is there another one?

**Comment by takahi-i** [comment]
Hi @stefanionescu, 

Thank you very much for trying RedPen.

You can use the customized XML configuration file for the RedPen server, since `validate` method supports to accept XML file as `config` parameter.

![screen shot 2017-06-13 at 9 53 38](https://user-images.githubusercontent.com/339436/27061381-634e844a-501e-11e7-9f45-86b9822dbac8.png)

You can see the detail usage in http://redpen.cc/docs/latest/index.html#server . Specifically you can try the validation with the custom XML file with local redpen server (localhost:8080) as follows.

```
$ curl --data document="Twas brillig and the slithy toves did gyre and gimble in the wabe" \
     --data lang=en --data format=PLAIN2 \
     --data config="`cat ./redpen-server/target/classes/conf/redpen-conf.xml`" \
     localhost:8080/rest/document/validate/
Line: 1, Offset: 0
    Sentence: Twas brillig and the slithy toves did gyre and gimble in the wabe
        Spelling: Found possibly misspelled word "brillig".
        Spelling: Found possibly misspelled word "slithy".
        Spelling: Found possibly misspelled word "toves".
        Spelling: Found possibly misspelled word "gyre".
        Spelling: Found possibly misspelled word "gimble".
        Spelling: Found possibly misspelled word "wabe".
        DoubledWord: Found repeated word "and".
```

**Comment by takahi-i** [comment]
Hi @stefanionescu I close this issue. Please let us know when you still have the problem reopening this issue.
