### ISSUE TITLE
Question about RedPen's check in order of validator

### ISSUE THREAD

**Issue by Y-Yasumoto** [redpen-cc/redpen#835]
When sentences are checked with RedPen, do you check it in order of validator 
defined with the conf file?
For instance, it is defined in the conf file on, "SuccessiveWord", "DuplicatedSection", and "SuggestExpression". 
When incompleteness concerning these three is detected in one sentences, is the output result 
output in following the order?

　Line: 142, Offset: 0
		Sentence: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			SuccessiveWord: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			DuplicatedSection: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			SuggestExpression: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			
Moreover, does the movement change by the version of RedPen?

**Comment by takahi-i** [comment]
@Y-Yasumoto currently the orders of errors from RedPen does not matches the order in configuration file. The validation process run from Document level validator to sentence level as the following code.

https://github.com/takahi-i/redpen/blob/c9664484949d30057f7b6567bbdfb4c9144a2927/redpen-core/src/main/java/cc/redpen/RedPen.java#L157-L159

I am not 100% sure but the order should be almost the same when you changes the versions, since we have not changed the code to apply validators to input documents.
